### ISSUE TITLE
A Small Bug 'java.lang.ArrayIndexOutOfBoundsException'

### ISSUE THREAD

**Issue by Albert-Gong** [rdegiovanni/mBERT#5]
Hi,
I find a small bug(or typo) in src/main/java/Main.java at line 39
```java
  if (method.contains(":")) {
      String [] ml = method.split(":");
      method = ml[0];
      line = Integer.parseInt(ml[2]);
  }
```
where m[2] should be ml[1].

Albert

**Comment by rdegiovanni** [comment]
Thanks for reporting this bug.
Fixed at commit [a18fc5d](https://github.com/rdegiovanni/mBERT/commit/a18fc5d68cec2cfcbfff5955c128156fc4ac047d).
Best,
Renzo
