### ISSUE TITLE
Doesn't work on a single java method

### ISSUE THREAD

**Issue by arghavanMor** [rdegiovanni/mBERT#6]
Hey,
I am trying to run mBERT on different java methods but it seems that it cannot accept a single method as an input source file. For example instead of a java class with different methods, If I put only the below method in the source file, It failed to execute:

```
public int min(int a, int b) {
	    if (a <= b)
            return a;
        else 
            return b;

    }
```

Is there any way to run it on a single method? I am using this command:
Error:
`java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0`

`./mBERT.sh -in=./method_sample/In/test.java -out=./method_sample/Out/ -N=4 -m=parse
`

**Comment by rdegiovanni** [comment]
Hello Arghavan,
Thanks for your interest in our tool.
The method's name is "min", so you have to use the flag -m=min.
If you have only one method in the file, then you can generate mutants for the entire file and it'll work as well.
Please, let me know if you mange to solve the issue.
Best,
Renzo
